### ISSUE TITLE
Coin, installed but don't get any emails.

### ISSUE THREAD

**Issue by ShaAlexander** [YunoHost-Apps/coin_ynh#26]
Hardware: AMD64

YunoHost version: 11.0.11 (stable).

I have access to my server : yes

Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : no

Description:

I’ve installed the app coin, but it does not send me the welcome e-mails or any other required mails to proceed with the installation. I couldn’t find any error messages or codes for this issue and is therefore not provided.

**Comment by Josue-T** [comment]
Should be probably fixed by #37 

Please open again if it still persist
