### ISSUE TITLE
postgresql

### ISSUE THREAD

**Issue by valog** [YunoHost-Apps/coin_ynh#3]
Hello

raspberry 3
Debian 8.0 32bit (Linux 4.9.51-v7+)
yunohost manual install (https://yunohost.org/#/install_manually_fr)
yunohost 2.7.2

sudo yunohost app install duniter --verbose
install break if postgresql is not installed.

Solution :
sudo apt-get install postgresql
sudo yunohost app install duniter --verbose

**Comment by alexAubin** [comment]
Hellow,

not sure to understand (you cite duniter?) but there was indeed an issue with the order of "init db" then "install deps". The following commit should have fixed the issue so I'm closing it.

Thanks for reporting !

https://github.com/YunoHost-Apps/coin_ynh/commit/80f35bdbc1fa93a807bdaec9533b2d3311df43ad
